### ISSUE TITLE
Adding Locations from User Citys

### ISSUE THREAD

**Issue by rygos** [Hifone/Hifone#104]
Hi,
maybe it es a good idea to adding the Locations from User Profiles to the location list in the Dashboard. Maybe with AutoCompletion in the Userprofile Settings.
This way, the admin dont needs to add them Manually to show the popular Location Widget.

**Comment by lianguan** [comment]
These are UGC.

**Comment by rygos** [comment]
Your right, may with moderation before using?
I think it is easier to moderate a List of Locations with something like a "unmoderated" flag than to enter Locations without a list with needed Locations.

Maybe there can be list in Dashboard who you can see a table with new Locations like:
Location, Used Count, Actions
New York, 23, EDIT/ACTIVATE/DELETE

With this you can Add Locations on a easier Way, and you leave it univisible until you activate it. Bevore activation you can Edit this Location. (example: From NewYork to New York) and Update the Location in every Profile the Wrong Spelling is used.

The Only tricky thing is to make sure that the system can move Wrong spelled Locations to the right one if the right one already activated =)

**Comment by lianguan** [comment]
Thank you very much.
There are many cities in the world, and not a limited list.
We should focus on how to check the user to fill out the name of the location, and then put these location names into the list hot locations.
