### ISSUE TITLE
Timezones dont work properly

### ISSUE THREAD

**Issue by rygos** [Hifone/Hifone#105]
Hi,
the Timezone Setting from Installation or APP_TIMEZONE in .env dont work.
It doesnt matter what i enter in this fields, the Postings or Replys getting the Chinese Timezone i think.

**Comment by lianguan** [comment]
You can set it in config/app.php manually.

**Comment by rygos** [comment]
Okay, this seems to work (after "php artisan hifone:update"), but why to set this option in installation?
Maybe it is better to change something like this in a external File linke ".env".
For .env there is no need to change it during development. config/app.php is (in my opinion) for setup the defult values.

**Comment by lianguan** [comment]
Fixed. 

see here #107
