### ISSUE TITLE
为啥不是基于5.1  LTS版本，而是5.2

### ISSUE THREAD

**Issue by xyzget** [Hifone/Hifone#106]
能告知原因吗？

**Comment by lianguan** [comment]
1. Hifone当前就处于dev状态，不推荐在正式环境使用。
2. 对于一个framework而言，5.2都已经经历这么多版本了，已经相对稳定。
3. 个人在版本选择上比较激进一些，5.2也有一些非常好的特性，如middleware等的改进。

**Comment by xyzget** [comment]
感谢您的答复，我也觉得 5.2 应该足够稳定了
