### ISSUE TITLE
timeAgo Setting

### ISSUE THREAD

**Issue by rygos** [Hifone/Hifone#108]
Hi,
i'm not sure, but i think the timeAgo Function for Postings are set in the following Line:
https://github.com/Hifone/Hifone/blob/e3717adc85f668acb7907e877d76322fd8b7f92b/resources/assets/coffee/forum.coffee#L146

i think this have to change to the prefered language and then gulp.
this way the script is hard to translate =)

Im not familiar with coffeescript, i dont know how to change this on runtime with active language. Maybe from App::getLocale() or from the <html lang""> Tag.

EDIT: I need this for Thread Meta Data like:  `1 小时前 • 4 Views`

**Comment by lianguan** [comment]
done.
