### ISSUE TITLE
Assistance needed: Activating 3. Party Authentication

### ISSUE THREAD

**Issue by rygos** [Hifone/Hifone#112]
Can you tell me how to activate the third party authentication (Github)?

i want to Translate the last views fur this, bit i want to test this before i create a pull request.

Sorry for Posting this as issue. =/

**Comment by lianguan** [comment]
hmm, A little bit complicated.

step 1. insert a record into table of providers

``` sql
MariaDB [hifone]> select * from providers;
+----+--------+--------+--------------+-------------+------------+------------+
| id | name   | slug   | icon         | description | created_at | updated_at |
+----+--------+--------+--------------+-------------+------------+------------+
|  1 | Github | github | fa fa-github | NULL        | NULL       | NULL       |
+----+--------+--------+--------------+-------------+------------+------------+
```

step 2. set github stuff in .env

``` shell
GITHUB_KEY=22877xxx
GITHUB_SECRET=ce859f5bbdxxx
GITHUB_REDIRECT_URI=http://hifone.com/auth/github/callback
```

step 3. php artisan config:cache

**Comment by rygos** [comment]
Okay. Done.
But the List with Alternative Login Providers (On Login Page) Does not show anything =)
I tried to fire artisan hifone:update too.
