### ISSUE TITLE
Dashboard: Changing the User Role are not working

### ISSUE THREAD

**Issue by rygos** [Hifone/Hifone#121]
If i cange the User Role in "Dashboard->User" Dropdown are not saved.

**Comment by lianguan** [comment]
fixed. please check it in the latest version of hifone.

**Comment by rygos** [comment]
You dont like the German Language, right? Now i have to translate everything again. =P

**Comment by lianguan** [comment]
Don't worry, it's not the right time to translate them. 😆

**Comment by rygos** [comment]
Yeah =)
If you want, i can create something like a Wiki Documentation English/German for Hifone installation, Update, and using. But this is a later Task =)

**Comment by lianguan** [comment]
Great, do what you want to do. 👍
