### ISSUE TITLE
每日登录获得积分 bug

### ISSUE THREAD

**Issue by abbychau** [Hifone/Hifone#126]
现在积分只挂在 UserWasLoggedinEvent 得到, 而该Event也只挂了在AuthController , 这样不先登出再登入就拿不到每天登录奖励了。

**Comment by lianguan** [comment]
已解决。

当前逻辑：用户回到首页就会启动积分累加机制。

**Comment by abbychau** [comment]
用HomeController 了呢! 其實我也真找不到一個合適的點來給予語義上的登入獎勵 :P
