### ISSUE TITLE
Request: How to Add Credits

### ISSUE THREAD

**Issue by rygos** [Hifone/Hifone#131]
I have tried some Credit things but i cannot get it to work, can you give a small howto?

**Comment by lianguan** [comment]
Credit rules are needed.

![image](https://cloud.githubusercontent.com/assets/15666864/17045973/1a7c8f96-5001-11e6-9924-debefadf44c9.png)

**Comment by rygos** [comment]
Okay, What means Frequency?

**Comment by lianguan** [comment]
@rygos 
for example:
login=> only allowed to add credits one time per day.
register=> only allowed to add credits once.
