### ISSUE TITLE
Suggestion: Improvements on Score Widget on Homepage

### ISSUE THREAD

**Issue by rygos** [Hifone/Hifone#132]
I have two Suggestions to the Score Widget on the Home Page.
1. Get rid of the Table Borders, this looks boring and has nothing todo with rest of the look of this page. My Suggestion Make DIV rows, without Column Titles.
   Column 1: Place Number (Like Now)
   Column 2: Avatar Icon (Like on Node-List), unter Avatar Icon place centered the Nickname
   Column 3: Points.

Use the row look like in the Statistics Widget.
1. The Second Suggestion is to Include the Avatar in Score Widget mentioned in point 1.

**Comment by rygos** [comment]
i can work on this Issue too if you want.

**Comment by lianguan** [comment]
@rygos 

Of cource. please do it.
