### ISSUE TITLE
Suggestion: TagCloud Widget Improvements

### ISSUE THREAD

**Issue by rygos** [Hifone/Hifone#134]
Hi, i think, there needs to be a Space between the Tag Name and the Use-Number.

How there is Hifone(239), Hifone (239) looks clearer.

More Space between the Tags. Like another Space.

**Comment by lianguan** [comment]
I think it is very easy to implement it . Could you send a PR?

**Comment by rygos** [comment]
Yes, before i send a Pull Request, i send some Screenshots of additional Ideas for this =) You can decide what looks better for you =)

**Comment by rygos** [comment]
![image](https://cloud.githubusercontent.com/assets/1985803/17049008/934d8ae0-4fea-11e6-977f-a435b4597567.png)

This is the my solution to this issue. Pull request in 2 minutes

**Comment by rygos** [comment]
Okay, i have some problems with my git stuff...

in _base.scss add after .badge-reply-count the following:

`.badge-tag-cloud{
  color: #333333;
}
`

then

in sidebar.blade.php

replace 
`<a href="/tag/{{ urlencode($tag->name) }}">{{ $tag->name }}</a>({{ $tag->count }})`

with

```
<div class="badge badge-tag-cloud">
<a href="/tag/{{ urlencode($tag->name) }}">{{ $tag->name }}</a>({{ $tag->count }})
</div>
```

Then it looks like in the Screenshot.
Sorry for this.

i have to delete my repo because of some mistakes i cannot revert =(
