### ISSUE TITLE
[WIP]PM System needs Atention

### ISSUE THREAD

**Issue by rygos** [Hifone/Hifone#146]
The PM System seems nearly finished. But i dont work.

**Comment by rygos** [comment]
I'm working on it =)

**Comment by lianguan** [comment]
:+1:

**Comment by rygos** [comment]
Okay, i have done some work:
![image](https://cloud.githubusercontent.com/assets/1985803/17401376/9c5d6fd4-5a4d-11e6-9163-d9a7b45ca7b4.png)
(PM Overview. You can read the Subjects and See Name & Avatar of Source-User. The Green Badge is for "Unreaded Messages" for Subject.)

![image](https://cloud.githubusercontent.com/assets/1985803/17401434/f4d8b7ea-5a4d-11e6-887f-aa9577042196.png)
On this View you can read the Discussion, you can add more User to this Discussion and Answer. Like normal Threads. =)

There are some things i have to complete until PullRequest:
- Widget for Homepage (Send Message button with Unreaded Count)
- Create new message
- User Selection with PullDown and Search

See you =)

**Comment by lianguan** [comment]
good job.

**Comment by rygos** [comment]
Okay. The Todo after the Pullrequest:
- Show for everyone the Avatar and Name of the User who is Recipient for the other. (Now you see only the name who starts the conversation.)
- Markdown Support for TEXT (second Column in Database for HTML data and make use of markdown lib.)
- Show Unreaded Messages count on Homescreen-Widget
- Integration to Notifications
- Integration to Credits system.
