### ISSUE TITLE
Cannot declare class CreateThreadsTable, because the name is already in use

### ISSUE THREAD

**Issue by clarifysky** [Hifone/Hifone#167]
When I execute `php artisan hifone:install`, this error appears, why?
![qq20160921-0](https://cloud.githubusercontent.com/assets/5001145/18696963/c094283a-7fef-11e6-919b-e7ad5925e7c4.png)

**Comment by lianguan** [comment]
@clwm01 

Are you running the [latest release](https://github.com/Hifone/Hifone/releases/latest) version of Hifone ?

**Comment by clarifysky** [comment]
@phecho  Yes, I'm running the latest release version. But I have solved this problem by clean the `migrations` folder and rerun `php artisan hifone:install` command.
