### ISSUE TITLE
php artisan hifone:install 时会报错

### ISSUE THREAD

**Issue by thinkcc** [Hifone/Hifone#181]
`[root@bogon Hifone]# /usr/local/php/bin/php artisan hifone:install
Clearing settings cache...
Settings cache cleared!
Backing up database...
Dumping database and uploading...

Successfully dumped mysql, compressed with gzip and store it to local at /home/wwwroot/default/Hifone/storage/app/2017-04-06_04.22.10
Backup completed!
Application key [base64:6BEAPJcha0WX4CQG0GNAUV+HSJ8EG8RL+w7que1yhGA=] set successfully.
Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
Copied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]
Copied Directory [/vendor/hifone/dashboard/src/config/administrator] To [/app/administrator]
Copied Directory [/vendor/hifone/dashboard/public] To [/public/packages/hifone/dashboard]
Copied Directory [/vendor/cmgmyr/messenger/src/migrations] To [/database/migrations]
Publishing complete for tag []!
PHP Fatal error:  Cannot declare class CreateThreadsTable, because the name is already in use in /home/wwwroot/default/Hifone/database/migrations/2016_05_29_013243_create_threads_table.php on line 66

                                                                               
  [Symfony\Component\Debug\Exception\FatalErrorException]                      
  Cannot declare class CreateThreadsTable, because the name is already in use  
                                                                               

                                                                               
  [Symfony\Component\Debug\Exception\FatalErrorException]                      
  Cannot declare class CreateThreadsTable, because the name is already in use  
                                                                               

                                                                               
  [Symfony\Component\Debug\Exception\FatalErrorException]                      
  Cannot declare class CreateThreadsTable, because the name is already in use  
                                                                               
`

存在这种问题，还望给予回复~！

**Comment by anyeyouming** [comment]
PHP7，同样的错误，还望指导，谢谢！

**Comment by anyeyouming** [comment]
删除Hifone/vendor/cmgmyr/messenger/src/migrations目录下所有的文件就可以不报此错误了。应该是表创建重复导致的。

**Comment by rygos** [comment]
this is a duplicated Migration because of the messenger package. they are using a migration with the same name as hifone.

**Comment by zhongyuankeji888** [comment]
我也是报这个错误，删除那些文件也是没有用的！

**Comment by gaojianqiu002** [comment]
删除 `Hifone/vendor/cmgmyr/messenger/src/migrations` 目录下的所有文件，删除`Hifone\database\migrations`目录下的重复文件，即可
delete the files of `Hifone/vendor/cmgmyr/messenger/src/migrations` directory,and!delete  the duplicated Migration in the `Hifone\database\migrations` directory,so,i delete `2014_10_28_175635_create_threads_table.php`,^_^,got it?

**Comment by mygetub** [comment]
这个有二次开发文档吗？
