### ISSUE TITLE
Cannot declare class CreateThreadsTable

### ISSUE THREAD

**Issue by loganfreeman** [Hifone/Hifone#184]
PHP Fatal error:  Cannot declare class CreateThreadsTable, because the name is already in use in database/migrations/2016_05_29_013243_create_threads_table.php on line 66

because it Copied Directory [/vendor/cmgmyr/messenger/src/migrations] To [/database/migrations]

`ls vendor/cmgmyr/messenger/src/migrations`

```
2014_10_28_175635_create_threads_table.php
2014_10_28_175710_create_messages_table.php
2014_10_28_180224_create_participants_table.php
2014_11_03_154831_add_soft_deletes_to_participants_table.php
2014_11_10_083449_add_nullable_to_last_read_in_participants_table.php
2014_11_20_131739_alter_last_read_in_participants_table.php
2014_12_04_124531_add_softdeletes_to_threads_table.php
```

**Comment by lianguan** [comment]
fixed
