### ISSUE TITLE
Error installation 

### ISSUE THREAD

**Issue by almokhtarbr** [Hifone/Hifone#187]
system：macOS Hight Sierra  10.13.4
php version：PHP 7.2.4 
mysql version：5.6
Production Environment

mbr:Hifone mbr$ php artisan generate:key 

PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /Users/jhon/Desktop/Hifone/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/Users/jhon/Des...', 51, Array)
#1 /Users/jhon/Desktop/Hifone/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /Users/jhon/Desktop/Hifone/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(50): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(ErrorException))
#3 /Users/jhon/Desktop/Hifone/bootstrap/cache/compiled.php(2163): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(ErrorException))
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
#5 {main}
  thrown in /Users/jhon/Desktop/Hifone/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51
PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /Users/jhon/Desktop/Hifone/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/Users/jhon/Des...', 51, Array)
#1 /Users/jhon/Desktop/Hifone/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /Users/jhon/Desktop/Hifone/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(50): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 /Users/jhon/Desktop/Hifone/bootstrap/cache/compiled.php(2163): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 /Users/jhon/Desktop/Hifone/bootstrap/cache/compiled.php(2181): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Ex in /Users/jhon/Desktop/Hifone/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51

**Comment by rygos** [comment]
I assume there is a Inkompatibility with php7.

I suggest to install PHP 5.6+

**Comment by almokhtarbr** [comment]
aah ok @rygos  thank you .
