### ISSUE TITLE
装不上是什么情况？？

### ISSUE THREAD

**Issue by phith0n** [Hifone/Hifone#20]
Linux，并非windows，.env都配好了，但执行php artisan migrate会出错……

```
/www # php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes



  [InvalidArgumentException]
  Database (/www/database/database.sqlite) does not exist.
```

**Comment by lianguan** [comment]
用sqlite?  文件不存在就touch一个。
- touch database/database.sqlite
- php artisan migrate
- php artisan hifone:seed

**Comment by phith0n** [comment]
额。。你这不是解决问题的方式。。
问题的根本在于，生产环境不用测试，为什么会用到sqlite。
另外，我按你的方法touch了文件，但执行php artisan migrate了之后，hifone就以sqlite为数据库了，但我在.env里配置的是mysql，这是为什么……

**Comment by lianguan** [comment]
@phith0n hifone支持sqlite,mysql...
.env修改之后，要记得php artisan config:cache
