### ISSUE TITLE
php artisan hifone:seed error

### ISSUE THREAD

**Issue by hefengbao** [Hifone/Hifone#23]
```
  php artisan hifone:seed

  [Symfony\Component\Console\Exception\InvalidArgumentException]
  The "force" option does not exist.
```

**Comment by magicpriest** [comment]
The same, take a log.

[2016-06-15 15:35:49] production.ERROR: Symfony\Component\Console\Exception\InvalidArgumentException: The "force" option does not exist. in /Users/alisa/Dev/hifone/vendor/symfony/console/Input/Input.php:190
Stack trace:
#0 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/Command.php(253): Symfony\Component\Console\Input\Input->getOption('force')
#1 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/ConfirmableTrait.php(23): Illuminate\Console\Command->option('force')
#2 /Users/alisa/Dev/hifone/app/Console/Commands/DemoSeederCommand.php(47): Hifone\Console\Commands\DemoSeederCommand->confirmToProceed()
#3 [internal function]: Hifone\Console\Commands\DemoSeederCommand->fire()
#4 /Users/alisa/Dev/hifone/bootstrap/cache/compiled.php(1257): call_user_func_array(Array, Array)
#5 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#6 /Users/alisa/Dev/hifone/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/alisa/Dev/hifone/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/alisa/Dev/hifone/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Hifone\Console\Commands\DemoSeederCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Users/alisa/Dev/hifone/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /Users/alisa/Dev/hifone/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main} {"identification":{"id":"58f2caf0-7991-4800-9326-bd37c2e31166"}} 
[2016-06-15 15:38:34] production.ERROR: Symfony\Component\Console\Exception\InvalidArgumentException: The "force" option does not exist. in /Users/alisa/Dev/hifone/vendor/symfony/console/Input/Input.php:190
Stack trace:
#0 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/Command.php(253): Symfony\Component\Console\Input\Input->getOption('force')
#1 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/ConfirmableTrait.php(23): Illuminate\Console\Command->option('force')
#2 /Users/alisa/Dev/hifone/app/Console/Commands/DemoSeederCommand.php(47): Hifone\Console\Commands\DemoSeederCommand->confirmToProceed()
#3 [internal function]: Hifone\Console\Commands\DemoSeederCommand->fire()
#4 /Users/alisa/Dev/hifone/bootstrap/cache/compiled.php(1257): call_user_func_array(Array, Array)
#5 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#6 /Users/alisa/Dev/hifone/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/alisa/Dev/hifone/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/alisa/Dev/hifone/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Hifone\Console\Commands\DemoSeederCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Users/alisa/Dev/hifone/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /Users/alisa/Dev/hifone/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main} {"identification":{"id":"19be469d-f4ea-4c18-b479-537be4fb944f"}} 
[2016-06-15 15:42:55] production.ERROR: Symfony\Component\Console\Exception\InvalidArgumentException: The "force" option does not exist. in /Users/alisa/Dev/hifone/vendor/symfony/console/Input/Input.php:190
Stack trace:
#0 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/Command.php(253): Symfony\Component\Console\Input\Input->getOption('force')
#1 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/ConfirmableTrait.php(23): Illuminate\Console\Command->option('force')
#2 /Users/alisa/Dev/hifone/app/Console/Commands/DemoSeederCommand.php(47): Hifone\Console\Commands\DemoSeederCommand->confirmToProceed()
#3 [internal function]: Hifone\Console\Commands\DemoSeederCommand->fire()
#4 /Users/alisa/Dev/hifone/bootstrap/cache/compiled.php(1257): call_user_func_array(Array, Array)
#5 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#6 /Users/alisa/Dev/hifone/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/alisa/Dev/hifone/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/alisa/Dev/hifone/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Hifone\Console\Commands\DemoSeederCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Users/alisa/Dev/hifone/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /Users/alisa/Dev/hifone/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main} {"identification":{"id":"f9215771-30c5-43a9-9000-62a3ea189e77"}} 
[2016-06-15 15:52:31] production.ERROR: Symfony\Component\Console\Exception\InvalidArgumentException: The "force" option does not exist. in /Users/alisa/Dev/hifone/vendor/symfony/console/Input/Input.php:190
Stack trace:
#0 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/Command.php(253): Symfony\Component\Console\Input\Input->getOption('force')
#1 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/ConfirmableTrait.php(23): Illuminate\Console\Command->option('force')
#2 /Users/alisa/Dev/hifone/app/Console/Commands/DemoSeederCommand.php(47): Hifone\Console\Commands\DemoSeederCommand->confirmToProceed()
#3 [internal function]: Hifone\Console\Commands\DemoSeederCommand->fire()
#4 /Users/alisa/Dev/hifone/bootstrap/cache/compiled.php(1257): call_user_func_array(Array, Array)
#5 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#6 /Users/alisa/Dev/hifone/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/alisa/Dev/hifone/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/alisa/Dev/hifone/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Hifone\Console\Commands\DemoSeederCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Users/alisa/Dev/hifone/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /Users/alisa/Dev/hifone/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main} {"identification":{"id":"8e2b29e7-8c94-4a5d-a0c5-a1742dfbad85"}} 
[2016-06-15 15:55:21] production.ERROR: Symfony\Component\Console\Exception\InvalidArgumentException: The "force" option does not exist. in /Users/alisa/Dev/hifone/vendor/symfony/console/Input/Input.php:190
Stack trace:
#0 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/Command.php(253): Symfony\Component\Console\Input\Input->getOption('force')
#1 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/ConfirmableTrait.php(23): Illuminate\Console\Command->option('force')
#2 /Users/alisa/Dev/hifone/app/Console/Commands/DemoSeederCommand.php(47): Hifone\Console\Commands\DemoSeederCommand->confirmToProceed()
#3 [internal function]: Hifone\Console\Commands\DemoSeederCommand->fire()
#4 /Users/alisa/Dev/hifone/bootstrap/cache/compiled.php(1257): call_user_func_array(Array, Array)
#5 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#6 /Users/alisa/Dev/hifone/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/alisa/Dev/hifone/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/alisa/Dev/hifone/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Hifone\Console\Commands\DemoSeederCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Users/alisa/Dev/hifone/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Users/alisa/Dev/hifone/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /Users/alisa/Dev/hifone/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main} {"identification":{"id":"4086f118-a337-45a8-bd87-199491b79689"}}

**Comment by lianguan** [comment]
- cp .env.example .env
- modify .env settings
- php artisan config:cache
- php artisan migrate
- php artisan key:generate
- php artisan config:cache
- php artisan hifone:seed

**Comment by magicpriest** [comment]
Hey, phecho.
I've done this steps on newly cloned repo, and last step throws this exception.
  [Symfony\Component\Console\Exception\InvalidArgumentException]
  The "force" option does not exist.

**Comment by lianguan** [comment]
@magicpriest 

By default Hifone comes with a .env.example file. You'll need to rename this file to just .env regardless of what environment you're working on.

If you're using SQLite then your .env file should not contain a DB_HOST key. You'll also need to touch ./database/hifone.sqlite and give it the required permissions.

**Comment by magicpriest** [comment]
@phecho 
I've already understand that and setuped .env for working with mysql, set user, password, but the issue is still there.

**Comment by magicpriest** [comment]
@phecho 
Issue is not solved, yet. Even with latest commits
