### ISSUE TITLE
An error has occurred and this resource cannot be displayed.

### ISSUE THREAD

**Issue by makeclan** [Hifone/Hifone#39]
安装最后一步提示

An error has occurred and this resource cannot be displayed.

**Comment by qinglang1208** [comment]
![Uploading image.png…]()

**Comment by makeclan** [comment]
执行 php artisan hifone:install 这个命令时报下面错误 导致的

  [PDOException]  
  SQLSTATE[HY000] [2002] No such file or directory  

已经通过http://www.jb51.net/article/81009.htm 解决
